services:
  db:
    container_name: todo_app_postgres
    image: postgres:15.1-alpine
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypass
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5332:5332"
    networks:
      - db
    restart: unless-stopped

networks:
  db:
    driver: bridge

volumes:
  db:

